// Do not modify this file. It's generated by Framework.Cli generate command.

namespace DatabaseIntegrate.Doc
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.Linq;
    using System.Threading.Tasks;
    using Framework.DataAccessLayer;
    using Database.Doc;

    public static class LanguageIntegrateApp
    {
        public enum IdEnum { [IdEnum(null)]None = 0, [IdEnum("English")]English = -1, [IdEnum("German")]German = -2 }

        public static LanguageIntegrate Row(this IdEnum value)
        {
            return RowList.Where(item => item.IdName == IdEnumAttribute.IdNameFromEnum(value)).SingleOrDefault();
        }

        public static IdEnum IdName(string value)
        {
            return IdEnumAttribute.IdNameToEnum<IdEnum>(value);
        }

        public static string IdName(this IdEnum value)
        {
            return IdEnumAttribute.IdNameFromEnum(value);
        }

        public static async Task<int> Id(this IdEnum value)
        {
            return (await Data.Query<LanguageIntegrate>().Where(item => item.IdName == IdEnumAttribute.IdNameFromEnum(value)).QueryExecuteAsync()).Single().Id;
        }

        public static List<LanguageIntegrate> RowList
        {
            get
            {
                var result = new List<LanguageIntegrate>
                {
                    new LanguageIntegrate { Id = 0, Name = "English", TextHtml = "<span class=\"flag-icon flag-icon-gb\"></span> English", IdName = "English" },
                    new LanguageIntegrate { Id = 0, Name = "German", TextHtml = "<span class=\"flag-icon flag-icon-de\"></span> German", IdName = "German" },
                };
                return result;
            }
        }
    }

    public static class LoginUserIntegrateApp
    {
        public enum IdEnum { [IdEnum(null)]None = 0, [IdEnum("a")]a = -1, [IdEnum("c")]c = -2, [IdEnum("d")]d = -3, [IdEnum("Guest")]Guest = -4 }

        public static LoginUserIntegrate Row(this IdEnum value)
        {
            return RowList.Where(item => item.IdName == IdEnumAttribute.IdNameFromEnum(value)).SingleOrDefault();
        }

        public static IdEnum IdName(string value)
        {
            return IdEnumAttribute.IdNameToEnum<IdEnum>(value);
        }

        public static string IdName(this IdEnum value)
        {
            return IdEnumAttribute.IdNameFromEnum(value);
        }

        public static async Task<int> Id(this IdEnum value)
        {
            return (await Data.Query<LoginUserIntegrate>().Where(item => item.IdName == IdEnumAttribute.IdNameFromEnum(value)).QueryExecuteAsync()).Single().Id;
        }

        public static List<LoginUserIntegrate> RowList
        {
            get
            {
                var result = new List<LoginUserIntegrate>
                {
                    new LoginUserIntegrate { Id = 0, Name = "a", Password = null, IsIntegrate = true, IsDelete = false, IdName = "a" },
                    new LoginUserIntegrate { Id = 0, Name = "c", Password = null, IsIntegrate = true, IsDelete = false, IdName = "c" },
                    new LoginUserIntegrate { Id = 0, Name = "d", Password = null, IsIntegrate = true, IsDelete = false, IdName = "d" },
                    new LoginUserIntegrate { Id = 0, Name = "Guest", Password = null, IsIntegrate = true, IsDelete = false, IdName = "Guest" },
                };
                return result;
            }
        }
    }

    public static class LoginRoleIntegrateApp
    {
        public enum IdEnum { [IdEnum(null)]None = 0, [IdEnum("Admin")]Admin = -1, [IdEnum("Customer")]Customer = -2, [IdEnum("Developer")]Developer = -3, [IdEnum("Guest")]Guest = -4, [IdEnum("Login")]Login = -5 }

        public static LoginRoleIntegrate Row(this IdEnum value)
        {
            return RowList.Where(item => item.IdName == IdEnumAttribute.IdNameFromEnum(value)).SingleOrDefault();
        }

        public static IdEnum IdName(string value)
        {
            return IdEnumAttribute.IdNameToEnum<IdEnum>(value);
        }

        public static string IdName(this IdEnum value)
        {
            return IdEnumAttribute.IdNameFromEnum(value);
        }

        public static async Task<int> Id(this IdEnum value)
        {
            return (await Data.Query<LoginRoleIntegrate>().Where(item => item.IdName == IdEnumAttribute.IdNameFromEnum(value)).QueryExecuteAsync()).Single().Id;
        }

        public static List<LoginRoleIntegrate> RowList
        {
            get
            {
                var result = new List<LoginRoleIntegrate>
                {
                    new LoginRoleIntegrate { Id = 0, Name = "Admin", Sort = 2, IdName = "Admin" },
                    new LoginRoleIntegrate { Id = 0, Name = "Customer", Sort = 4, IdName = "Customer" },
                    new LoginRoleIntegrate { Id = 0, Name = "Developer", Sort = 1, IdName = "Developer" },
                    new LoginRoleIntegrate { Id = 0, Name = "Guest", Sort = 3, IdName = "Guest" },
                    new LoginRoleIntegrate { Id = 0, Name = "Login", Sort = 5, IdName = "Login" },
                };
                return result;
            }
        }
    }
}
